name: RevivePeople
version: "${project.version}"
main: me.bot.MainPlugin
api-version: 1.19
authors: []
description: test


commands:
  kit:
    description: Your description
    usage: /kit [?nickname]
    permission: yourplugin.yourcommandpermission

  revive:
    description: Your description
    usage: /revive nickname
    permission: yourplugin.yourcommandpermission